name=CAN With Mode
version=0.3.2
author=Sandeep Mistry <sandeep.mistry@gmail.com>
maintainer=Amir Hododi <amirhododi@gmail.com>
sentence=An Arduino library for sending and receiving data using CAN bus.
paragraph=Supports Microchip MCP2515 based boards/shields and the Espressif ESP32's built-in SJA1000 compatible CAN controller.
category=Communication
url=https://github.com/BluestarCo/arduino-CAN
architectures=*
includes=CAN.h
